parameters: 
    container.class: Hubsine\Framework\DependencyInjection\Container
    loader_factory.class: Hubsine\Framework\DependencyInjection\Loader\LoaderFactory
    session.class: Hubsine\Framework\Http\Session
    request.class: Hubsine\Framework\Http\Request
    base.controller.class: Hubsine\Framework\http\Controller\BaseController
#    validator.class: DMarketPlace\Framework\Validator\Validator
#    base.controller.class: DMarketPlace\Framework\Controller\BaseController
#    controller.resolver.class: DMarketPlace\Framework\Controller\Resolver\ControllerResolver     
#    shortcode.seller.class: DMarketPlace\Shortcode\SellerShortcode
#    form.factory.class: DMarketPlace\Framework\Form\FormFactory
#    twig.class: DMarketPlace\Framework\Twig\Twig
#    form_theme: 
#        - form_div_layout.html.twig 
#        - bootstrap_3_layout.html.twig
#        - form_table_layout.html.twig
#    #http://symfony.com/doc/current/form/form_customization.html#form-customization-form-themes
#    repository.manager.class: DMarketPlace\Framework\Repository\RepositoryManager
#    #repository.base.class: DMarketPlace\Framework\Repository\BaseRepository
#    #mapping.annotation_manager.class: DMarketPlace\Framework\Mapping\MappingAnnotationManager
#    translator.class: DMarketPlace\Translator
#    wp.roles_caps.class: DMarketPlace\WpRolesCaps
#    swift.mailer.class: DMarketPlace\Framework\Mailer\SwiftMailer
#    swift.message.class: DMarketPlace\Framework\Mailer\SwiftMessage
#    
##    mailer.param:
##        - transport: 
##            - MailTransport
##            - SendMailTransport
##            - SmtpTransport 
##        #SmtpTransport peut prendre en paramètre smtp.gmail.com
##        - host: smtp.gmail.com
##        - user: shonen.shojo@gmail.com
##        - password: 16781741
##        - from_default: contact@wpsilex.com
##        - from_register: register@wpsilex.com
#    
#    locale: fr