services:
    container:
        class: %container.class%
        synthetic: true 
    loader.factory:
        class: %loader_factory.class%
        synthetic: true
        arguments: ['@container']
    session:
        class: %session.class%
        synthetic: true
    request:
        class: %request.class%
        synthetic: true
    base.controller:
        class: %base.controller.class%
        calls: 
            - [setContainer, ['@container']]
    translator:
        class: %translator.class%
        synthetic: true
#    validator.builder:
#        class: %validator.builder.class%
    validator.factory:
        class: %validator.factory.class%
        synthetic: true
    form.factory:
        class: %form.factory.class%
        #synthetic: true
        arguments: ['@validator.factory']
    templating.twig:
        class: %templating.twig.class%
        arguments: ['@request', '@translator']
    templating.php:
        class: %templating.php.class%
    templating: 
        class: %templating.class%
        arguments: ['@templating.twig','@templating.php']
    mailer:
        class: %mailer.class%
    entity.manager: 
        class: %entity.manager.class%

        
